//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public int Id { get; set; }
        public string Identificator { get; set; }
        public int NumberOfSeats { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> DeletionDate { get; set; }
    }
}
