//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryItem
    {
        public int Id { get; set; }
        public string PLName { get; set; }
        public string ENName { get; set; }
        public string PLDescription { get; set; }
        public string ENDescription { get; set; }
    }
}
