//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTime
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public int GroupId { get; set; }
        public int DayOfWeekId { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DayOfWeek DayOfWeek { get; set; }
        public virtual Group Group { get; set; }
    }
}
