//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LanguageSchoolEntities : DbContext
    {
        public LanguageSchoolEntities()
            : base("name=LanguageSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactRequest> ContactRequests { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<EntryTest> EntryTests { get; set; }
        public virtual DbSet<LessonSubject> LessonSubjects { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<ClosedQuestion> ClosedQuestions { get; set; }
        public virtual DbSet<OpenQuestion> OpenQuestions { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestsLessonSubject> TestsLessonSubjects { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserOpenAnswer> UserOpenAnswers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersCourses> UsersCourses { get; set; }
        public virtual DbSet<UsersTests> UsersTests1 { get; set; }
    }
}
