//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.UsersMessages = new HashSet<UserMessage>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Header { get; set; }
        public string Contents { get; set; }
        public int MessageTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual DictionaryItem Role { get; set; }
        public virtual DictionaryItem MessageType { get; set; }
        public virtual Course Course { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMessage> UsersMessages { get; set; }
    }
}
