//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClosedAnswer
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public int TestClosedQuestionId { get; set; }
        public int AnswerId { get; set; }
        public bool IsCorrect { get; set; }
        public int UserTestId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual TestClosedQuestion TestClosedQuestion { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
        public virtual UserTest UserTest { get; set; }
    }
}
