//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOpenAnswer
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public int UserId { get; set; }
        public int OpenQuestionId { get; set; }
        public string Content { get; set; }
        public int Points { get; set; }
        public string Comment { get; set; }
        public bool IsMarked { get; set; }
        public int UserTestId { get; set; }
    
        public virtual OpenQuestion OpenQuestion { get; set; }
        public virtual User User { get; set; }
        public virtual UserTest UserTest { get; set; }
    }
}
